// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Read directly (not via prisma's throwing `env()` helper) so that
    // `prisma generate` works during the Docker build, where DATABASE_URL
    // isn't set yet. It's only actually needed at runtime for `migrate deploy`.
    url: process.env.DATABASE_URL ?? "",
  },
});
 